In [1]:
import numpy as np

In [13]:
dim = 3


P2 = np.ones((dim,dim))/(dim)

P2p = np.eye(dim) - np.ones((dim,dim))/(dim)

P1 = np.ones((dim,dim))/(dim)
P1[0,0] = P1[1,1] = 1/(dim) +0.2
P1[0,1] = P1[1,0] = 1/(dim) - 0.2


A = np.zeros((dim,dim))/dim
A[0,0] = A[1,1] = 0.25
A[0,1] = A[1,0] = 0.75
print(P1)
print(P2)
print(P2p)
print(A)

[[0.53333333 0.13333333 0.33333333]
 [0.13333333 0.53333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
[[0.25 0.75 0.  ]
 [0.75 0.25 0.  ]
 [0.   0.   0.  ]]


In [14]:
k=200

dif = (A@P1) - (A@P2)
dif_origin = (P1) - (P2)
print(dif)

print(np.linalg.norm(dif))
print(np.linalg.norm(dif_origin))

[[-0.1  0.1  0. ]
 [ 0.1 -0.1  0. ]
 [ 0.   0.   0. ]]
0.20000000000000007
0.4


In [24]:
A= np.random.rand(dim,dim)
A = A@A.T

print(A)
A2 = A - np.mean(A)
A1 = A - A2
print(A)
print(((P2)@(A2 )@(P1-P2)@A2@P2))

[[0.71288401 0.52864701 0.16174242]
 [0.52864701 0.4357178  0.11114751]
 [0.16174242 0.11114751 0.04062022]]
[[0.71288401 0.52864701 0.16174242]
 [0.52864701 0.4357178  0.11114751]
 [0.16174242 0.11114751 0.04062022]]
[[0.00238727 0.00238727 0.00238727]
 [0.00238727 0.00238727 0.00238727]
 [0.00238727 0.00238727 0.00238727]]


In [78]:
print((P2@P2@P2@P2@P2@P2))

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
